FROM python:3.9

WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y \
  build-essential \
  libgl1 \
  libglib2.0-0 \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000

CMD ["python", "main.py"]